# Generated by Django 5.1 on 2024-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_remove_donation_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja pozarządowa', 'Organizacja Pozarządowa'), ('zbiórka lokalna', 'Zbiórka Lokalna')], default='fundacja', max_length=25)),
                ('categories', models.ManyToManyField(to='main.category')),
            ],
        ),
    ]
