# Generated by Django 5.1 on 2024-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='help_groups',
            field=models.ManyToManyField(related_name='institutions', to='main.helpgroup'),
        ),
        migrations.AddField(
            model_name='institution',
            name='voivodeships',
            field=models.ManyToManyField(related_name='institutions', to='main.voivodeship'),
        ),
    ]
