# Generated by Django 5.1 on 2024-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_helpgroup_voivodeship_institution_help_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='help_groups',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='voivodeships',
        ),
        migrations.DeleteModel(
            name='HelpGroup',
        ),
        migrations.DeleteModel(
            name='Voivodeship',
        ),
    ]
