# Generated by Django 5.1 on 2024-08-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_institution_help_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
