# Generated by Django 5.1 on 2024-08-31 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_institution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
