# Generated by Django 5.1 on 2024-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
