# Generated by Django 5.1 on 2024-09-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='is_picked_up',
            new_name='is_taken',
        ),
    ]
