# Generated by Django 5.1 on 2024-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_is_picked_up_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='taken_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
